name: 🐞 Bug Report
# title: " "
description: Problems with a Notebook
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a  Notebooks 🐞 Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/semilleroCV/deep-learning-notes/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the  Notebooks [issues](https://github.com/semilleroCV/deep-learning-notes/issues) and found no similar bug report.
          required: true

  - type: textarea
    attributes:
      label: Notebook name
      description: Please let us know which of our Notebooks you are referring to in your Bug Report.
      placeholder: |
        💡 ProTip! Provide link or name to Notebook that you are referring to.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.
      placeholder: |
        - Google Colab / Kaggle / Local
        - OS: Ubuntu 22.04
        - Python: 3.10.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.
        This is referred to by community members as creating a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/semilleroCV/deep-learning-notes/pulls) (PR) to help improve  Notebooks for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the  Notebooks [Contributing Guide](https://github.com/semilleroCV/deep-learning-notes/blob/main/CONTRIBUTING.md) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
        