name: 🚀 Pull Request
on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Submit Pull Request
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const yaml = require('js-yaml');

            const PR_TEMPLATE_PATH = '.github/PULL_REQUEST_TEMPLATE.md';
            const prTemplate = yaml.safeLoad(fs.readFileSync(PR_TEMPLATE_PATH, 'utf8'));

            const prTitle = prTemplate['Pull Request Title'];
            const prDescription = prTemplate['Description'];
            const prChecklist = prTemplate['Checklist'];
            const prLinkedIssues = prTemplate['Linked Issues'];
            const prAdditionalInfo = prTemplate['Additional Information'];

            const body = `
${prTemplate['Thank you message']}
### Pull Request Title
${prTitle}

### Description
${prDescription}

### Checklist
${prChecklist.map(item => `- [${item.label}] ${item.required ? '**(Required)**' : ''}`).join('\n')}

### Linked Issues
${prLinkedIssues}

### Additional Information
${prAdditionalInfo}
`;

            const params = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: body
            };

            await github.pulls.update(params);
